### ISSUE TITLE
Have Toil to distribute CWL workflow jobs between multiple chronos endpoints, on different clusters

### ISSUE THREAD

**Issue by theferrit32** [theferrit32/toil#3]
Toil can already manage job execution order, and job parallelism, as long as all worker processes have read/write access to a shared "jobStore" directory.

Assuming each cluster being used has a filesystem mounted with this jobStore directory, toil should be able to issue chronos jobs that can communicate with each other and the master toil process, because each toil worker process run by the chronos jobs will write its state to the same shared jobStore on that filesystem.

----

#### Easier way
This can be implemented in the Chronos BatchSystem by providing a CSV list of Chronos endpoints to use in the TOIL_CHRONOS_ENDPOINT environment variable. 

`TOIL_CHRONOS_ENDPOINT="host1,host2,host3"` 

The ChronosBatchSystem can then distribute jobs evenly between the endpoints.

Even if the section below is changed or not implemented, the functionality here is still likely useful and should be implemented as another option if the user does not care about directing individual workflow steps to specific endpoints.

----

#### Other way
It can also be desirable to have more fine grained usage of the different clusters though.  If one workflow step uses files all hosted within one cluster, it can be more performant to run the job for that step against the chronos endpoint for that cluster.

Idea

For each step in a CWL workflow, allow the specification of an associated cloud endpoint (chronos) to use in executing that step. 

Possible ideas:
- for each file used, associate a cloud endpoint url. In chronos batchSystem, determine which endpoint to use based on the set of endpoint urls from all the files used by a particular job.
- for each step in CWL, take as an input the endpoint url, as a separate input field in the job YAML file.  If no endpoints are specified for that step, send it to any of the available endpoints.  This method is probably doable as long as all the yaml values are sent through to the batch system.  It could be an issue because the file1_endpoint field is not actually used in the CWL file, so it might be thrown away. 
    - ```yaml
       file1:
         class: File
         path: <...>
       file1_endpoint: <...>
       ```
- Define a [custom type](http://www.commonwl.org/user_guide/19-custom-types/) in the CWL file, for example "cloud-file-resource" which acts similarly to the CWL "File" class, but has additional fields for endpoint specification
    - ```yaml
       file1:
         type: chronos-types.yml#cloud-file-resource
         path: <...>
         endpoint: <...>
      ```
